name: Deploy to GitHub Pages

permissions:
  contents: write
  id-token: write

on:
  push:
    branches: [ main ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v5.2.0
      with:
        dotnet-version: 10.0.x

    - name: Install WASM workload
      run: dotnet workload install wasm-tools
      
    - name: Set base href for GitHub Pages
      run: sed -i 's|<base href="/" />|<base href="/TM_MappingTools/" />|g' TM_MappingTools/wwwroot/index.html

    - name: Publish .NET Core Project
      run: dotnet publish TM_MappingTools.csproj -c Release -o release --nologo

    - name: Copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html

    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll

    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.8.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
        clean: true

